tasks:
  - init: |
      curl -sS https://starship.rs/install.sh > /tmp/install.sh
      sh /tmp/install.sh --yes
      echo 'eval "$(starship init bash)"' >> ${HOME}/.bashrc
      cp -r ${GITPOD_REPO_ROOT}/.config/* ${HOME}/.config/
    command: |
      composer install

image:
  file: .gitpod.Dockerfile

jetbrains:
  phpstorm:
    vmoptions: '-Xmx4g'
  plugins:
    - com.github.copilot
    - com.intellij.kubernetes
    - com.intellij.mermaid
    - ru.adelf.idea.dotenv
    - org.toml.lang

vscode:
  extensions:
    - ikappas.composer
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - getpsalm.psalm-vscode-plugin
    - SonarSource.sonarlint-vscode
    - recca0120.vscode-phpunit
