tasks:
  - init: |
      echo "No special initialization"
    command: |
      composer install

image:
  file: .gitpod/Dockerfile

jetbrains:
  phpstorm:
    vmoptions: '-Xmx4g'
  plugins:
    - com.github.copilot
    - com.intellij.kubernetes
    - com.intellij.mermaid
    - ru.adelf.idea.dotenv

vscode:
  extensions:
    - ikappas.composer
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - getpsalm.psalm-vscode-plugin
    - SonarSource.sonarlint-vscode
    - recca0120.vscode-phpunit
